# Generated by Django 5.0.2 on 2024-03-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_likedproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedproducts',
            old_name='recipe',
            new_name='item',
        ),
    ]
