# Generated by Django 5.0.2 on 2024-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
