# Generated by Django 5.0.2 on 2024-02-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_item_sub_category_delete_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
