# Generated by Django 5.0.2 on 2024-02-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sub_category',
            new_name='category_name',
        ),
    ]
