# Generated by Django 5.0.2 on 2024-02-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_item_quantity_item_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_choice',
            new_name='category_type',
        ),
    ]
