# Generated by Django 5.0.2 on 2024-03-02 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_item_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='products.category'),
        ),
    ]
